package saskia.dbpedia

class DBpediaProperty {
	
   static String propertyPrefix = "http://dbpedia.org/ontology/"

   String ontologyProperty
   
   public DBpediaProperty(String property) {
	ontologyProperty = getShortName(property)
   }

/** Get a full DBpedia property name, if it's not already in full format.
	 * @param name the DBpedia property name 
	 * @return the full DBpedia property name
	 */
	static String getFullName(String name) {
		return (name?.startsWith(propertyPrefix) ? name : propertyPrefix+name)
	}
    
	String getFullName() {
		return DBpediaProperty.getFullName(ontologyProperty)
	}
	
	/** Get a short DBpedia property name, if it's not already in short format.
	 * @param name the DBpedia property name 
	 * @return the short DBpedia property name
	 */
	static String getShortName(String name) {
		return  (name?.startsWith(propertyPrefix) ? name.replaceAll(/${propertyPrefix}/, "") : name)
	}
	
// grep "<owl:ObjectProperty " dbpedia_3.4.owl | grep -oP "http://[^\"]*" | sort

/*
http://dbpedia.org/ontology/Actor/arielAward
http://dbpedia.org/ontology/Actor/geminiAward
http://dbpedia.org/ontology/Actor/goldenCalfAward
http://dbpedia.org/ontology/Actor/goldenRaspberryAward
http://dbpedia.org/ontology/Actor/iftaAward
http://dbpedia.org/ontology/Actor/laurenceOlivierAward
http://dbpedia.org/ontology/Actor/naacpImageAward
http://dbpedia.org/ontology/Actor/nationalFilmAward
http://dbpedia.org/ontology/Actor/screenActorsGuildAward
http://dbpedia.org/ontology/Aircraft/nationalOrigin
http://dbpedia.org/ontology/Aircraft/type
http://dbpedia.org/ontology/Airline/alliance
http://dbpedia.org/ontology/Airline/destination
http://dbpedia.org/ontology/Airline/headquarter
http://dbpedia.org/ontology/Airline/hubAirport
http://dbpedia.org/ontology/Airline/lounge
http://dbpedia.org/ontology/Airline/targetAirport
http://dbpedia.org/ontology/Album/compiler
http://dbpedia.org/ontology/Album/director
http://dbpedia.org/ontology/Album/producer
http://dbpedia.org/ontology/AnatomicalStructure/artery
http://dbpedia.org/ontology/AnatomicalStructure/lymph
http://dbpedia.org/ontology/AnatomicalStructure/nerve
http://dbpedia.org/ontology/AnatomicalStructure/precursor
http://dbpedia.org/ontology/AnatomicalStructure/vein
http://dbpedia.org/ontology/Architect/significantBuilding
http://dbpedia.org/ontology/Architect/significantDesign
http://dbpedia.org/ontology/Architect/significantProject
http://dbpedia.org/ontology/Area/area
http://dbpedia.org/ontology/Area/arrondissement
http://dbpedia.org/ontology/Area/canton
http://dbpedia.org/ontology/Area/commune
http://dbpedia.org/ontology/Area/department
http://dbpedia.org/ontology/Area/memberOfParliament
http://dbpedia.org/ontology/Area/twinCity
http://dbpedia.org/ontology/Area/twinCountry
http://dbpedia.org/ontology/Artery/branchFrom
http://dbpedia.org/ontology/Artery/branchTo
http://dbpedia.org/ontology/Artery/supplies
http://dbpedia.org/ontology/Artist/academyAward
http://dbpedia.org/ontology/Artist/afiAward
http://dbpedia.org/ontology/Artist/associatedAct
http://dbpedia.org/ontology/Artist/baftaAward
http://dbpedia.org/ontology/Artist/cesarAward
http://dbpedia.org/ontology/Artist/currentMember
http://dbpedia.org/ontology/Artist/emmyAward
http://dbpedia.org/ontology/Artist/field
http://dbpedia.org/ontology/Artist/filmFareAward
http://dbpedia.org/ontology/Artist/genre
http://dbpedia.org/ontology/Artist/goldenGlobeAward
http://dbpedia.org/ontology/Artist/goyaAward
http://dbpedia.org/ontology/Artist/grammyAward
http://dbpedia.org/ontology/Artist/instrument
http://dbpedia.org/ontology/Artist/label
http://dbpedia.org/ontology/Artist/movement
http://dbpedia.org/ontology/Artist/pastMember
http://dbpedia.org/ontology/Artist/tonyAward
http://dbpedia.org/ontology/Artist/training
http://dbpedia.org/ontology/Artist/voiceType
http://dbpedia.org/ontology/Astronaut/mission
http://dbpedia.org/ontology/Astronaut/selection
http://dbpedia.org/ontology/Astronaut/type
http://dbpedia.org/ontology/Athlete/currentTeam
http://dbpedia.org/ontology/Athlete/formerTeam
http://dbpedia.org/ontology/Automobile/assembly
http://dbpedia.org/ontology/Automobile/bodyStyle
http://dbpedia.org/ontology/Automobile/class
http://dbpedia.org/ontology/Automobile/designer
http://dbpedia.org/ontology/Automobile/engine
http://dbpedia.org/ontology/Automobile/layout
http://dbpedia.org/ontology/Automobile/parentCompany
http://dbpedia.org/ontology/Automobile/platform
http://dbpedia.org/ontology/Automobile/relatedAutomobile
http://dbpedia.org/ontology/AutomobileEngine/blockAlloy
http://dbpedia.org/ontology/AutomobileEngine/configuration
http://dbpedia.org/ontology/AutomobileEngine/coolingSystem
http://dbpedia.org/ontology/AutomobileEngine/fuelSystem
http://dbpedia.org/ontology/AutomobileEngine/fuelType
http://dbpedia.org/ontology/AutomobileEngine/headAlloy
http://dbpedia.org/ontology/AutomobileEngine/oilSystem
http://dbpedia.org/ontology/AutomobileEngine/valvetrain
http://dbpedia.org/ontology/AutomobilePlatform/assembly
http://dbpedia.org/ontology/AutomobilePlatform/bodyStyle
http://dbpedia.org/ontology/AutomobilePlatform/class
http://dbpedia.org/ontology/AutomobilePlatform/engine
http://dbpedia.org/ontology/AutomobilePlatform/layout
http://dbpedia.org/ontology/AutomobilePlatform/relatedAutomobilePlatform
http://dbpedia.org/ontology/AutomobilePlatform/vehicle
http://dbpedia.org/ontology/Award/country
http://dbpedia.org/ontology/BadmintonPlayer/coach
http://dbpedia.org/ontology/BadmintonPlayer/event
http://dbpedia.org/ontology/Band/associatedBand
http://dbpedia.org/ontology/Band/associatedMusicalArtist
http://dbpedia.org/ontology/Band/currentMember
http://dbpedia.org/ontology/Band/instrument
http://dbpedia.org/ontology/Band/label
http://dbpedia.org/ontology/Band/pastMember
http://dbpedia.org/ontology/Band/voiceType
http://dbpedia.org/ontology/BaseballPlayer/statisticLabel
http://dbpedia.org/ontology/BasketballPlayer/college
http://dbpedia.org/ontology/BasketballPlayer/draftTeam
http://dbpedia.org/ontology/BasketballPlayer/highschool
http://dbpedia.org/ontology/BasketballPlayer/league
http://dbpedia.org/ontology/Beverage/distributor
http://dbpedia.org/ontology/Beverage/manufacturer
http://dbpedia.org/ontology/Beverage/origin
http://dbpedia.org/ontology/Beverage/related
http://dbpedia.org/ontology/Beverage/variant
http://dbpedia.org/ontology/BodyOfWater/city
http://dbpedia.org/ontology/BodyOfWater/country
http://dbpedia.org/ontology/BodyOfWater/district
http://dbpedia.org/ontology/BodyOfWater/region
http://dbpedia.org/ontology/BodyOfWater/state
http://dbpedia.org/ontology/Book/country
http://dbpedia.org/ontology/Book/coverArtist
http://dbpedia.org/ontology/Book/illustrator
http://dbpedia.org/ontology/Book/mediaType
http://dbpedia.org/ontology/Book/series
http://dbpedia.org/ontology/Book/subject
http://dbpedia.org/ontology/Book/translator
http://dbpedia.org/ontology/Brain/component
http://dbpedia.org/ontology/Brain/isPartOf
http://dbpedia.org/ontology/Bridge/crosses
http://dbpedia.org/ontology/Bridge/locatedInArea
http://dbpedia.org/ontology/BritishRoyalty/royalAnthem
http://dbpedia.org/ontology/Broadcast/broadcastArea
http://dbpedia.org/ontology/Broadcast/country
http://dbpedia.org/ontology/Broadcast/language
http://dbpedia.org/ontology/Broadcast/network
http://dbpedia.org/ontology/Broadcast/sisterStation
http://dbpedia.org/ontology/Building/architect
http://dbpedia.org/ontology/Building/architectualBureau
http://dbpedia.org/ontology/Building/architecturalStyle
http://dbpedia.org/ontology/Building/awards
http://dbpedia.org/ontology/Building/owner
http://dbpedia.org/ontology/Building/owningOrganisation
http://dbpedia.org/ontology/Building/structuralSystem
http://dbpedia.org/ontology/Building/tenant
http://dbpedia.org/ontology/Canal/branch
http://dbpedia.org/ontology/Canal/branchOf
http://dbpedia.org/ontology/Canal/company
http://dbpedia.org/ontology/Canal/endPoint
http://dbpedia.org/ontology/Canal/engineer
http://dbpedia.org/ontology/Canal/hasJunctionWith
http://dbpedia.org/ontology/Canal/originalEndPoint
http://dbpedia.org/ontology/Canal/originalStartPoint
http://dbpedia.org/ontology/Canal/principalEngineer
http://dbpedia.org/ontology/Canal/startPoint
http://dbpedia.org/ontology/City/administrativeCollectivity
http://dbpedia.org/ontology/City/administrativeDistrict
http://dbpedia.org/ontology/City/associationOfLocalGovernment
http://dbpedia.org/ontology/City/country
http://dbpedia.org/ontology/City/department
http://dbpedia.org/ontology/City/federalState
http://dbpedia.org/ontology/City/frazioni
http://dbpedia.org/ontology/City/jointCommunity
http://dbpedia.org/ontology/City/largestMetro
http://dbpedia.org/ontology/City/province
http://dbpedia.org/ontology/City/region
http://dbpedia.org/ontology/City/region1
http://dbpedia.org/ontology/City/saint
http://dbpedia.org/ontology/City/twinCity
http://dbpedia.org/ontology/City/twinCountry
http://dbpedia.org/ontology/College/sisterCollege
http://dbpedia.org/ontology/CollegeCoach/coachedTeam
http://dbpedia.org/ontology/CollegeCoach/college
http://dbpedia.org/ontology/Comedian/americanComedyAward
http://dbpedia.org/ontology/Comedian/britishComedyAwards
http://dbpedia.org/ontology/Comedian/olivierAward
http://dbpedia.org/ontology/Comedian/peabodyAward
http://dbpedia.org/ontology/Company/areaServed
http://dbpedia.org/ontology/Company/division
http://dbpedia.org/ontology/Company/industry
http://dbpedia.org/ontology/Company/language
http://dbpedia.org/ontology/Company/owner
http://dbpedia.org/ontology/Company/parentCompany
http://dbpedia.org/ontology/Company/product
http://dbpedia.org/ontology/Company/service
http://dbpedia.org/ontology/Company/subsidiary
http://dbpedia.org/ontology/Country/anthem
http://dbpedia.org/ontology/Country/governmentType
http://dbpedia.org/ontology/Cricketer/country
http://dbpedia.org/ontology/Currency/usingcountry
http://dbpedia.org/ontology/Device/manufacturer
http://dbpedia.org/ontology/Device/predecessor
http://dbpedia.org/ontology/Device/successor
http://dbpedia.org/ontology/EducationalInstitution/city
http://dbpedia.org/ontology/EducationalInstitution/country
http://dbpedia.org/ontology/EducationalInstitution/county
http://dbpedia.org/ontology/EducationalInstitution/dean
http://dbpedia.org/ontology/EducationalInstitution/director
http://dbpedia.org/ontology/EducationalInstitution/head
http://dbpedia.org/ontology/EducationalInstitution/principal
http://dbpedia.org/ontology/EducationalInstitution/province
http://dbpedia.org/ontology/EducationalInstitution/rector
http://dbpedia.org/ontology/EducationalInstitution/sport
http://dbpedia.org/ontology/EducationalInstitution/state
http://dbpedia.org/ontology/EducationalInstitution/superintendent
http://dbpedia.org/ontology/Embryology/system
http://dbpedia.org/ontology/EthnicGroup/language
http://dbpedia.org/ontology/EthnicGroup/populationPlace
http://dbpedia.org/ontology/EthnicGroup/related
http://dbpedia.org/ontology/EthnicGroup/religion
http://dbpedia.org/ontology/Event/country
http://dbpedia.org/ontology/Event/followingEvent
http://dbpedia.org/ontology/Event/genre
http://dbpedia.org/ontology/Event/location
http://dbpedia.org/ontology/Event/previousEvent
http://dbpedia.org/ontology/FigureSkater/choreographer
http://dbpedia.org/ontology/FigureSkater/coach
http://dbpedia.org/ontology/FigureSkater/country
http://dbpedia.org/ontology/FigureSkater/currentPartner
http://dbpedia.org/ontology/FigureSkater/formerChoreographer
http://dbpedia.org/ontology/FigureSkater/formerCoach
http://dbpedia.org/ontology/FigureSkater/formerPartner
http://dbpedia.org/ontology/FigureSkater/skatingClub
http://dbpedia.org/ontology/Film/cinematography
http://dbpedia.org/ontology/Film/country
http://dbpedia.org/ontology/Film/director
http://dbpedia.org/ontology/Film/distributor
http://dbpedia.org/ontology/Film/editing
http://dbpedia.org/ontology/Film/music
http://dbpedia.org/ontology/Film/narrator
http://dbpedia.org/ontology/Film/producer
http://dbpedia.org/ontology/Film/starring
http://dbpedia.org/ontology/Film/writer
http://dbpedia.org/ontology/FilmFestival/closingFilm
http://dbpedia.org/ontology/FilmFestival/director
http://dbpedia.org/ontology/FilmFestival/film
http://dbpedia.org/ontology/FilmFestival/language
http://dbpedia.org/ontology/FilmFestival/openingFilm
http://dbpedia.org/ontology/FilmFestival/producer
http://dbpedia.org/ontology/FilmFestival/starring
http://dbpedia.org/ontology/FilmFestival/writer
http://dbpedia.org/ontology/FootballPlayer/coachingTeam
http://dbpedia.org/ontology/FootballPlayer/college
http://dbpedia.org/ontology/FootballPlayer/debutTeam
http://dbpedia.org/ontology/FootballPlayer/highschool
http://dbpedia.org/ontology/FootballPlayer/pastTeam
http://dbpedia.org/ontology/FootballPlayer/team
http://dbpedia.org/ontology/FootballTeam/chairman
http://dbpedia.org/ontology/FootballTeam/city
http://dbpedia.org/ontology/FootballTeam/coach
http://dbpedia.org/ontology/FootballTeam/generalManager
http://dbpedia.org/ontology/FootballTeam/owner
http://dbpedia.org/ontology/FootballTeam/president
http://dbpedia.org/ontology/FootballTeam/teamOwner
http://dbpedia.org/ontology/FootballTeam/teamPresident
http://dbpedia.org/ontology/FormulaOneRacer/firstRace
http://dbpedia.org/ontology/FormulaOneRacer/firstWin
http://dbpedia.org/ontology/FormulaOneRacer/lastRace
http://dbpedia.org/ontology/FormulaOneRacer/lastWin
http://dbpedia.org/ontology/GaelicGamesPlayer/sport
http://dbpedia.org/ontology/GrandPrix/fastestDriver
http://dbpedia.org/ontology/GrandPrix/fastestDriverCountry
http://dbpedia.org/ontology/GrandPrix/fastestDriverTeam
http://dbpedia.org/ontology/GrandPrix/firstDriver
http://dbpedia.org/ontology/GrandPrix/firstDriverCountry
http://dbpedia.org/ontology/GrandPrix/firstDriverTeam
http://dbpedia.org/ontology/GrandPrix/poleDriver
http://dbpedia.org/ontology/GrandPrix/poleDriverCountry
http://dbpedia.org/ontology/GrandPrix/poleDriverTeam
http://dbpedia.org/ontology/GrandPrix/secondDriver
http://dbpedia.org/ontology/GrandPrix/secondDriverCountry
http://dbpedia.org/ontology/GrandPrix/secondTeam
http://dbpedia.org/ontology/GrandPrix/thirdDriver
http://dbpedia.org/ontology/GrandPrix/thirdDriverCountry
http://dbpedia.org/ontology/GrandPrix/thirdTeam
http://dbpedia.org/ontology/GrandPrix/type
http://dbpedia.org/ontology/Grape/notableWine
http://dbpedia.org/ontology/Grape/origin
http://dbpedia.org/ontology/Grape/wineRegion
http://dbpedia.org/ontology/HistoricPlace/architect
http://dbpedia.org/ontology/Hospital/country
http://dbpedia.org/ontology/Hospital/region
http://dbpedia.org/ontology/Hospital/state
http://dbpedia.org/ontology/IceHockeyPlayer/draftTeam
http://dbpedia.org/ontology/IceHockeyPlayer/league
http://dbpedia.org/ontology/IceHockeyPlayer/prospectTeam
http://dbpedia.org/ontology/IceHockeyPlayer/whaDraftTeam
http://dbpedia.org/ontology/Infrastructure/previousInfrastructure
http://dbpedia.org/ontology/Infrastructure/subsequentInfrastructure
http://dbpedia.org/ontology/Island/archipelago
http://dbpedia.org/ontology/Island/country
http://dbpedia.org/ontology/Island/majorIsland
http://dbpedia.org/ontology/Lake/inflow
http://dbpedia.org/ontology/Lake/island
http://dbpedia.org/ontology/Lake/outflow
http://dbpedia.org/ontology/Language/region
http://dbpedia.org/ontology/Language/states
http://dbpedia.org/ontology/LaunchPad/associatedRocket
http://dbpedia.org/ontology/LaunchPad/firstLaunchRocket
http://dbpedia.org/ontology/LaunchPad/lastLaunchRocket
http://dbpedia.org/ontology/LaunchPad/launchSite
http://dbpedia.org/ontology/LaunchPad/operator
http://dbpedia.org/ontology/Legislature/house
http://dbpedia.org/ontology/Legislature/leader
http://dbpedia.org/ontology/Legislature/meetingBuilding
http://dbpedia.org/ontology/Legislature/meetingCity
http://dbpedia.org/ontology/Lymph/drainsFrom
http://dbpedia.org/ontology/Lymph/drainsTo
http://dbpedia.org/ontology/Magazine/editor
http://dbpedia.org/ontology/Magazine/previousEditor
http://dbpedia.org/ontology/MeanOfTransportation/manufacturer
http://dbpedia.org/ontology/MeanOfTransportation/predecessor
http://dbpedia.org/ontology/MeanOfTransportation/successor
http://dbpedia.org/ontology/MilitaryConflict/commander
http://dbpedia.org/ontology/MilitaryConflict/partOf
http://dbpedia.org/ontology/MilitaryConflict/place
http://dbpedia.org/ontology/MilitaryConflict/territory
http://dbpedia.org/ontology/MilitaryPerson/allegiance
http://dbpedia.org/ontology/MilitaryPerson/battles
http://dbpedia.org/ontology/MilitaryPerson/branch
http://dbpedia.org/ontology/MilitaryPerson/commands
http://dbpedia.org/ontology/MilitaryPerson/militaryRank
http://dbpedia.org/ontology/MilitaryPerson/unit
http://dbpedia.org/ontology/MilitaryUnit/aircraftAttack
http://dbpedia.org/ontology/MilitaryUnit/aircraftBomber
http://dbpedia.org/ontology/MilitaryUnit/aircraftElectronic
http://dbpedia.org/ontology/MilitaryUnit/aircraftFigther
http://dbpedia.org/ontology/MilitaryUnit/aircraftHelicopter
http://dbpedia.org/ontology/MilitaryUnit/aircraftHelicopterAttack
http://dbpedia.org/ontology/MilitaryUnit/aircraftHelicopterCargo
http://dbpedia.org/ontology/MilitaryUnit/aircraftHelicopterMultirole
http://dbpedia.org/ontology/MilitaryUnit/aircraftHelicopterObservation
http://dbpedia.org/ontology/MilitaryUnit/aircraftHelicopterTransport
http://dbpedia.org/ontology/MilitaryUnit/aircraftHelicopterUtility
http://dbpedia.org/ontology/MilitaryUnit/aircraftInterceptor
http://dbpedia.org/ontology/MilitaryUnit/aircraftPatrol
http://dbpedia.org/ontology/MilitaryUnit/aircraftRecon
http://dbpedia.org/ontology/MilitaryUnit/aircraftTrainer
http://dbpedia.org/ontology/MilitaryUnit/aircraftTransport
http://dbpedia.org/ontology/MilitaryUnit/battle
http://dbpedia.org/ontology/MilitaryUnit/branch
http://dbpedia.org/ontology/MilitaryUnit/commandStructure
http://dbpedia.org/ontology/MilitaryUnit/commander
http://dbpedia.org/ontology/MilitaryUnit/country
http://dbpedia.org/ontology/MilitaryUnit/garrison
http://dbpedia.org/ontology/MilitaryUnit/march
http://dbpedia.org/ontology/MilitaryUnit/notableCommander
http://dbpedia.org/ontology/MilitaryUnit/patron
http://dbpedia.org/ontology/MilitaryUnit/secondCommander
http://dbpedia.org/ontology/MilitaryUnit/thirdCommander
http://dbpedia.org/ontology/Monarch/heir
http://dbpedia.org/ontology/Monarch/placeOfBurial
http://dbpedia.org/ontology/Monarch/royalAnthem
http://dbpedia.org/ontology/Municipality/neighboringMunicipality
http://dbpedia.org/ontology/MusicGenre/derivative
http://dbpedia.org/ontology/MusicGenre/instrument
http://dbpedia.org/ontology/MusicGenre/musicFusionGenre
http://dbpedia.org/ontology/MusicGenre/musicSubgenre
http://dbpedia.org/ontology/MusicGenre/stylisticOrigin
http://dbpedia.org/ontology/Musical/lyrics
http://dbpedia.org/ontology/Musical/musicBy
http://dbpedia.org/ontology/MusicalArtist/associatedBand
http://dbpedia.org/ontology/MusicalArtist/associatedMusicalArtist
http://dbpedia.org/ontology/MusicalWork/artist
http://dbpedia.org/ontology/MusicalWork/label
http://dbpedia.org/ontology/MusicalWork/recordPlace
http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete/college
http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete/formerHighschool
http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete/highschool
http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete/sport
http://dbpedia.org/ontology/Nerve/branchFrom
http://dbpedia.org/ontology/Nerve/branchTo
http://dbpedia.org/ontology/Nerve/innervates
http://dbpedia.org/ontology/Newspaper/associateEditor
http://dbpedia.org/ontology/Newspaper/chiefEditor
http://dbpedia.org/ontology/Newspaper/editor
http://dbpedia.org/ontology/Newspaper/format
http://dbpedia.org/ontology/Newspaper/headquarters
http://dbpedia.org/ontology/Newspaper/managingEditor
http://dbpedia.org/ontology/Newspaper/owner
http://dbpedia.org/ontology/Newspaper/sisterNewspaper
http://dbpedia.org/ontology/OfficeHolder/otherParty
http://dbpedia.org/ontology/OlympicResult/flagBearer
http://dbpedia.org/ontology/OlympicResult/nationalOlympicCommittee
http://dbpedia.org/ontology/OlympicResult/otherAppearances
http://dbpedia.org/ontology/OlympicResult/summerAppearances
http://dbpedia.org/ontology/OlympicResult/winterAppearances
http://dbpedia.org/ontology/Olympics/officialOpenedBy
http://dbpedia.org/ontology/Olympics/olympicOathSwornByAthlete
http://dbpedia.org/ontology/Olympics/olympicOathSwornByJudge
http://dbpedia.org/ontology/Olympics/torchBearer
http://dbpedia.org/ontology/Organisation/affiliation
http://dbpedia.org/ontology/Organisation/foundationOrganisation
http://dbpedia.org/ontology/Organisation/foundationPerson
http://dbpedia.org/ontology/Organisation/foundationPlace
http://dbpedia.org/ontology/Organisation/genre
http://dbpedia.org/ontology/Organisation/keyPerson
http://dbpedia.org/ontology/Organisation/location
http://dbpedia.org/ontology/Organisation/locationCity
http://dbpedia.org/ontology/Organisation/locationCountry
http://dbpedia.org/ontology/Organisation/owningCompany
http://dbpedia.org/ontology/Organisation/product
http://dbpedia.org/ontology/Organisation/type
http://dbpedia.org/ontology/Person/almaMater
http://dbpedia.org/ontology/Person/award
http://dbpedia.org/ontology/Person/birthPlace
http://dbpedia.org/ontology/Person/boards
http://dbpedia.org/ontology/Person/child
http://dbpedia.org/ontology/Person/citizenship
http://dbpedia.org/ontology/Person/deathCause
http://dbpedia.org/ontology/Person/deathPlace
http://dbpedia.org/ontology/Person/education
http://dbpedia.org/ontology/Person/employer
http://dbpedia.org/ontology/Person/ethnicity
http://dbpedia.org/ontology/Person/father
http://dbpedia.org/ontology/Person/homeTown
http://dbpedia.org/ontology/Person/influenced
http://dbpedia.org/ontology/Person/influencedBy
http://dbpedia.org/ontology/Person/knownFor
http://dbpedia.org/ontology/Person/mother
http://dbpedia.org/ontology/Person/nationality
http://dbpedia.org/ontology/Person/occupation
http://dbpedia.org/ontology/Person/partner
http://dbpedia.org/ontology/Person/party
http://dbpedia.org/ontology/Person/predecessor
http://dbpedia.org/ontology/Person/relation
http://dbpedia.org/ontology/Person/relative
http://dbpedia.org/ontology/Person/religion
http://dbpedia.org/ontology/Person/residence
http://dbpedia.org/ontology/Person/restingPlace
http://dbpedia.org/ontology/Person/spouse
http://dbpedia.org/ontology/Person/successor
http://dbpedia.org/ontology/Place/location
http://dbpedia.org/ontology/Place/nearestCity
http://dbpedia.org/ontology/Place/type
http://dbpedia.org/ontology/Planet/discoverer
http://dbpedia.org/ontology/PokerPlayer/hometown
http://dbpedia.org/ontology/PopulatedPlace/capital
http://dbpedia.org/ontology/PopulatedPlace/ethnicGroup
http://dbpedia.org/ontology/PopulatedPlace/foundingPerson
http://dbpedia.org/ontology/PopulatedPlace/language
http://dbpedia.org/ontology/PopulatedPlace/languageType
http://dbpedia.org/ontology/PopulatedPlace/largestCity
http://dbpedia.org/ontology/PopulatedPlace/largestSettlement
http://dbpedia.org/ontology/PopulatedPlace/largestSettlementType
http://dbpedia.org/ontology/PopulatedPlace/leaderName
http://dbpedia.org/ontology/PopulatedPlace/leaderParty
http://dbpedia.org/ontology/PopulatedPlace/regionalLanguage
http://dbpedia.org/ontology/Race/firstWinner
http://dbpedia.org/ontology/Race/mostWinner
http://dbpedia.org/ontology/Race/recentWinner
http://dbpedia.org/ontology/RadioStation/area
http://dbpedia.org/ontology/RadioStation/city
http://dbpedia.org/ontology/RadioStation/format
http://dbpedia.org/ontology/RadioStation/owner
http://dbpedia.org/ontology/RadioStation/sisterStation
http://dbpedia.org/ontology/RecordLabel/country
http://dbpedia.org/ontology/RecordLabel/distributingCompany
http://dbpedia.org/ontology/RecordLabel/distributingLabel
http://dbpedia.org/ontology/RecordLabel/parent
http://dbpedia.org/ontology/River/mouth
http://dbpedia.org/ontology/River/mouthCountry
http://dbpedia.org/ontology/River/mouthDistrict
http://dbpedia.org/ontology/River/mouthMountain
http://dbpedia.org/ontology/River/mouthPlace
http://dbpedia.org/ontology/River/mouthRegion
http://dbpedia.org/ontology/River/mouthState
http://dbpedia.org/ontology/River/sourceCountry
http://dbpedia.org/ontology/River/sourceDistrict
http://dbpedia.org/ontology/River/sourceMountain
http://dbpedia.org/ontology/River/sourcePlace
http://dbpedia.org/ontology/River/sourceRegion
http://dbpedia.org/ontology/River/sourceState
http://dbpedia.org/ontology/Road/beltwayCity
http://dbpedia.org/ontology/Road/city
http://dbpedia.org/ontology/Road/county
http://dbpedia.org/ontology/Road/ruralMunicipality
http://dbpedia.org/ontology/Road/spurType
http://dbpedia.org/ontology/Road/state
http://dbpedia.org/ontology/Road/system
http://dbpedia.org/ontology/Rocket/comparable
http://dbpedia.org/ontology/Rocket/countryOrigin
http://dbpedia.org/ontology/Rocket/launchSite
http://dbpedia.org/ontology/RugbyPlayer/school
http://dbpedia.org/ontology/RugbyPlayer/university
http://dbpedia.org/ontology/Saint/beatifiedBy
http://dbpedia.org/ontology/Saint/beatifiedPlace
http://dbpedia.org/ontology/Saint/canonizedBy
http://dbpedia.org/ontology/Saint/canonizedPlace
http://dbpedia.org/ontology/Saint/majorShrine
http://dbpedia.org/ontology/Saint/veneratedIn
http://dbpedia.org/ontology/School/actingHeadteacher
http://dbpedia.org/ontology/School/administrator
http://dbpedia.org/ontology/School/alumni
http://dbpedia.org/ontology/School/chairperson
http://dbpedia.org/ontology/School/chaplain
http://dbpedia.org/ontology/School/custodian
http://dbpedia.org/ontology/School/denomination
http://dbpedia.org/ontology/School/district
http://dbpedia.org/ontology/School/executiveHeadteacher
http://dbpedia.org/ontology/School/headteacher
http://dbpedia.org/ontology/School/language
http://dbpedia.org/ontology/School/nobelLaureates
http://dbpedia.org/ontology/School/president
http://dbpedia.org/ontology/School/region
http://dbpedia.org/ontology/School/religion
http://dbpedia.org/ontology/School/rival
http://dbpedia.org/ontology/School/trustee
http://dbpedia.org/ontology/School/vicePrincipal
http://dbpedia.org/ontology/Scientist/academicAdvisor
http://dbpedia.org/ontology/Scientist/doctoralAdvisor
http://dbpedia.org/ontology/Scientist/doctoralStudent
http://dbpedia.org/ontology/Scientist/notableStudent
http://dbpedia.org/ontology/Single/album
http://dbpedia.org/ontology/Single/format
http://dbpedia.org/ontology/Single/musicalArtist
http://dbpedia.org/ontology/Single/musicalBand
http://dbpedia.org/ontology/Single/producer
http://dbpedia.org/ontology/Single/writer
http://dbpedia.org/ontology/SiteOfSpecialScientificInterest/areaOfSearch
http://dbpedia.org/ontology/Skyscraper/contractor
http://dbpedia.org/ontology/Skyscraper/developer
http://dbpedia.org/ontology/Skyscraper/engineer
http://dbpedia.org/ontology/Skyscraper/management
http://dbpedia.org/ontology/SoccerClub/ceo
http://dbpedia.org/ontology/SoccerClub/chairman
http://dbpedia.org/ontology/SoccerClub/clubsRecordGoalscorer
http://dbpedia.org/ontology/SoccerClub/ground
http://dbpedia.org/ontology/SoccerClub/honours
http://dbpedia.org/ontology/SoccerClub/manager
http://dbpedia.org/ontology/SoccerPlayer/club
http://dbpedia.org/ontology/SoccerPlayer/managerClub
http://dbpedia.org/ontology/SoccerPlayer/nationalTeam
http://dbpedia.org/ontology/SoccerPlayer/youthClub
http://dbpedia.org/ontology/Software/developer
http://dbpedia.org/ontology/Software/license
http://dbpedia.org/ontology/Software/operatingSystem
http://dbpedia.org/ontology/Software/platform
http://dbpedia.org/ontology/Software/programmingLanguage
http://dbpedia.org/ontology/Song/album
http://dbpedia.org/ontology/Song/composer
http://dbpedia.org/ontology/Song/producer
http://dbpedia.org/ontology/Song/writer
http://dbpedia.org/ontology/SpaceMission/booster
http://dbpedia.org/ontology/SpaceMission/crewMember
http://dbpedia.org/ontology/SpaceMission/landingvehicle
http://dbpedia.org/ontology/SpaceMission/launchPad
http://dbpedia.org/ontology/SpaceMission/launchvehicle
http://dbpedia.org/ontology/SpaceMission/lunarRover
http://dbpedia.org/ontology/SpaceMission/nextMission
http://dbpedia.org/ontology/SpaceMission/previousMission
http://dbpedia.org/ontology/SpaceMission/shuttle
http://dbpedia.org/ontology/SpaceMission/spacecraft
http://dbpedia.org/ontology/SpaceShuttle/country
http://dbpedia.org/ontology/SpaceShuttle/firstFlight
http://dbpedia.org/ontology/SpaceShuttle/lastFlight
http://dbpedia.org/ontology/SpaceShuttle/namedAfter
http://dbpedia.org/ontology/Spacecraft/crew
http://dbpedia.org/ontology/Spacecraft/launchSite
http://dbpedia.org/ontology/Spacecraft/organisation
http://dbpedia.org/ontology/Spacecraft/port1
http://dbpedia.org/ontology/Spacecraft/port2
http://dbpedia.org/ontology/Spacecraft/rocket
http://dbpedia.org/ontology/Spacecraft/station
http://dbpedia.org/ontology/Spacecraft/type
http://dbpedia.org/ontology/Species/binomial
http://dbpedia.org/ontology/Species/binomialAuthority
http://dbpedia.org/ontology/Species/class
http://dbpedia.org/ontology/Species/division
http://dbpedia.org/ontology/Species/domain
http://dbpedia.org/ontology/Species/family
http://dbpedia.org/ontology/Species/genus
http://dbpedia.org/ontology/Species/kingdom
http://dbpedia.org/ontology/Species/order
http://dbpedia.org/ontology/Species/phylum
http://dbpedia.org/ontology/Species/species
http://dbpedia.org/ontology/Station/platform
http://dbpedia.org/ontology/TelevisionEpisode/director
http://dbpedia.org/ontology/TelevisionEpisode/executiveProducer
http://dbpedia.org/ontology/TelevisionEpisode/guest
http://dbpedia.org/ontology/TelevisionEpisode/music
http://dbpedia.org/ontology/TelevisionEpisode/photographer
http://dbpedia.org/ontology/TelevisionEpisode/series
http://dbpedia.org/ontology/TelevisionEpisode/show
http://dbpedia.org/ontology/TelevisionEpisode/writer
http://dbpedia.org/ontology/TelevisionShow/channel
http://dbpedia.org/ontology/TelevisionShow/coExecutiveProducer
http://dbpedia.org/ontology/TelevisionShow/coProducer
http://dbpedia.org/ontology/TelevisionShow/composer
http://dbpedia.org/ontology/TelevisionShow/country
http://dbpedia.org/ontology/TelevisionShow/creativeDirector
http://dbpedia.org/ontology/TelevisionShow/creator
http://dbpedia.org/ontology/TelevisionShow/developer
http://dbpedia.org/ontology/TelevisionShow/director
http://dbpedia.org/ontology/TelevisionShow/distributor
http://dbpedia.org/ontology/TelevisionShow/editor
http://dbpedia.org/ontology/TelevisionShow/endingTheme
http://dbpedia.org/ontology/TelevisionShow/executiveProducer
http://dbpedia.org/ontology/TelevisionShow/network
http://dbpedia.org/ontology/TelevisionShow/openingTheme
http://dbpedia.org/ontology/TelevisionShow/presenter
http://dbpedia.org/ontology/TelevisionShow/producer
http://dbpedia.org/ontology/TelevisionShow/related
http://dbpedia.org/ontology/TelevisionShow/starring
http://dbpedia.org/ontology/TelevisionShow/storyEditor
http://dbpedia.org/ontology/TelevisionShow/voice
http://dbpedia.org/ontology/TennisPlayer/country
http://dbpedia.org/ontology/TradeUnion/country
http://dbpedia.org/ontology/University/athletics
http://dbpedia.org/ontology/University/campus
http://dbpedia.org/ontology/University/chairman
http://dbpedia.org/ontology/University/chancellor
http://dbpedia.org/ontology/University/officerInCharge
http://dbpedia.org/ontology/University/president
http://dbpedia.org/ontology/University/provost
http://dbpedia.org/ontology/University/viceChancellor
http://dbpedia.org/ontology/University/vicePresident
http://dbpedia.org/ontology/Vein/drainsFrom
http://dbpedia.org/ontology/Vein/drainsTo
http://dbpedia.org/ontology/VideoGame/artist
http://dbpedia.org/ontology/VideoGame/composer
http://dbpedia.org/ontology/VideoGame/developer
http://dbpedia.org/ontology/VideoGame/platform
http://dbpedia.org/ontology/VideoGame/writer
http://dbpedia.org/ontology/Weapon/placeOfOrigin
http://dbpedia.org/ontology/Weapon/type
http://dbpedia.org/ontology/Weapon/wars
http://dbpedia.org/ontology/Website/owner
http://dbpedia.org/ontology/WineRegion/growingGrape
http://dbpedia.org/ontology/WineRegion/partOfWineRegion
http://dbpedia.org/ontology/WineRegion/similar
http://dbpedia.org/ontology/WineRegion/subregion
http://dbpedia.org/ontology/WineRegion/varietals
http://dbpedia.org/ontology/WineRegion/wineProduced
http://dbpedia.org/ontology/Work/author
http://dbpedia.org/ontology/Work/award
http://dbpedia.org/ontology/Work/basedOn
http://dbpedia.org/ontology/Work/genre
http://dbpedia.org/ontology/Work/language
http://dbpedia.org/ontology/Work/previousWork
http://dbpedia.org/ontology/Work/publisher
http://dbpedia.org/ontology/Work/subsequentWork
http://dbpedia.org/ontology/Work/type
http://dbpedia.org/ontology/WorldHeritageSite/region
http://dbpedia.org/ontology/Wrestler/billed
http://dbpedia.org/ontology/Wrestler/resides
http://dbpedia.org/ontology/Wrestler/trainer
http://dbpedia.org/ontology/WrestlingEvent/brand
http://dbpedia.org/ontology/WrestlingEvent/promotion
http://dbpedia.org/ontology/Writer/notableWork
http://dbpedia.org/ontology/YearInSpaceflight/countryWithFirstAstronaut
http://dbpedia.org/ontology/YearInSpaceflight/countryWithFirstSatellite
http://dbpedia.org/ontology/YearInSpaceflight/countryWithFirstSatelliteLaunched
http://dbpedia.org/ontology/YearInSpaceflight/countryWithFirstSpaceflight
http://dbpedia.org/ontology/YearInSpaceflight/maidenFlightRocket
http://dbpedia.org/ontology/YearInSpaceflight/retiredRocket
http://dbpedia.org/ontology/academicAdvisor
http://dbpedia.org/ontology/academyAward
http://dbpedia.org/ontology/actingHeadteacher
http://dbpedia.org/ontology/administrativeCollectivity
http://dbpedia.org/ontology/administrativeDistrict
http://dbpedia.org/ontology/administrator
http://dbpedia.org/ontology/affiliation
http://dbpedia.org/ontology/afiAward
http://dbpedia.org/ontology/aircraftAttack
http://dbpedia.org/ontology/aircraftBomber
http://dbpedia.org/ontology/aircraftElectronic
http://dbpedia.org/ontology/aircraftFigther
http://dbpedia.org/ontology/aircraftHelicopter
http://dbpedia.org/ontology/aircraftHelicopterAttack
http://dbpedia.org/ontology/aircraftHelicopterCargo
http://dbpedia.org/ontology/aircraftHelicopterMultirole
http://dbpedia.org/ontology/aircraftHelicopterObservation
http://dbpedia.org/ontology/aircraftHelicopterTransport
http://dbpedia.org/ontology/aircraftHelicopterUtility
http://dbpedia.org/ontology/aircraftInterceptor
http://dbpedia.org/ontology/aircraftPatrol
http://dbpedia.org/ontology/aircraftRecon
http://dbpedia.org/ontology/aircraftTrainer
http://dbpedia.org/ontology/aircraftTransport
http://dbpedia.org/ontology/album
http://dbpedia.org/ontology/allegiance
http://dbpedia.org/ontology/alliance
http://dbpedia.org/ontology/almaMater
http://dbpedia.org/ontology/alumni
http://dbpedia.org/ontology/americanComedyAward
http://dbpedia.org/ontology/anthem
http://dbpedia.org/ontology/archipelago
http://dbpedia.org/ontology/architect
http://dbpedia.org/ontology/architectualBureau
http://dbpedia.org/ontology/architecturalStyle
http://dbpedia.org/ontology/area
http://dbpedia.org/ontology/areaOfSearch
http://dbpedia.org/ontology/areaServed
http://dbpedia.org/ontology/arielAward
http://dbpedia.org/ontology/arrondissement
http://dbpedia.org/ontology/artery
http://dbpedia.org/ontology/artist
http://dbpedia.org/ontology/assembly
http://dbpedia.org/ontology/associateEditor
http://dbpedia.org/ontology/associatedAct
http://dbpedia.org/ontology/associatedBand
http://dbpedia.org/ontology/associatedMusicalArtist
http://dbpedia.org/ontology/associatedRocket
http://dbpedia.org/ontology/associationOfLocalGovernment
http://dbpedia.org/ontology/athletics
http://dbpedia.org/ontology/author
http://dbpedia.org/ontology/award
http://dbpedia.org/ontology/awards
http://dbpedia.org/ontology/baftaAward
http://dbpedia.org/ontology/basedOn
http://dbpedia.org/ontology/battle
http://dbpedia.org/ontology/battles
http://dbpedia.org/ontology/beatifiedBy
http://dbpedia.org/ontology/beatifiedPlace
http://dbpedia.org/ontology/beltwayCity
http://dbpedia.org/ontology/billed
http://dbpedia.org/ontology/binomial
http://dbpedia.org/ontology/binomialAuthority
http://dbpedia.org/ontology/birthPlace
http://dbpedia.org/ontology/blockAlloy
http://dbpedia.org/ontology/boards
http://dbpedia.org/ontology/bodyStyle
http://dbpedia.org/ontology/booster
http://dbpedia.org/ontology/branch
http://dbpedia.org/ontology/branchFrom
http://dbpedia.org/ontology/branchOf
http://dbpedia.org/ontology/branchTo
http://dbpedia.org/ontology/brand
http://dbpedia.org/ontology/britishComedyAwards
http://dbpedia.org/ontology/broadcastArea
http://dbpedia.org/ontology/campus
http://dbpedia.org/ontology/canonizedBy
http://dbpedia.org/ontology/canonizedPlace
http://dbpedia.org/ontology/canton
http://dbpedia.org/ontology/capital
http://dbpedia.org/ontology/ceo
http://dbpedia.org/ontology/cesarAward
http://dbpedia.org/ontology/chairman
http://dbpedia.org/ontology/chairperson
http://dbpedia.org/ontology/chancellor
http://dbpedia.org/ontology/channel
http://dbpedia.org/ontology/chaplain
http://dbpedia.org/ontology/chiefEditor
http://dbpedia.org/ontology/child
http://dbpedia.org/ontology/choreographer
http://dbpedia.org/ontology/cinematography
http://dbpedia.org/ontology/citizenship
http://dbpedia.org/ontology/city
http://dbpedia.org/ontology/class
http://dbpedia.org/ontology/closingFilm
http://dbpedia.org/ontology/club
http://dbpedia.org/ontology/clubsRecordGoalscorer
http://dbpedia.org/ontology/coExecutiveProducer
http://dbpedia.org/ontology/coProducer
http://dbpedia.org/ontology/coach
http://dbpedia.org/ontology/coachedTeam
http://dbpedia.org/ontology/coachingTeam
http://dbpedia.org/ontology/college
http://dbpedia.org/ontology/commandStructure
http://dbpedia.org/ontology/commander
http://dbpedia.org/ontology/commands
http://dbpedia.org/ontology/commune
http://dbpedia.org/ontology/company
http://dbpedia.org/ontology/comparable
http://dbpedia.org/ontology/compiler
http://dbpedia.org/ontology/component
http://dbpedia.org/ontology/composer
http://dbpedia.org/ontology/configuration
http://dbpedia.org/ontology/contractor
http://dbpedia.org/ontology/coolingSystem
http://dbpedia.org/ontology/country
http://dbpedia.org/ontology/countryOrigin
http://dbpedia.org/ontology/countryWithFirstAstronaut
http://dbpedia.org/ontology/countryWithFirstSatellite
http://dbpedia.org/ontology/countryWithFirstSatelliteLaunched
http://dbpedia.org/ontology/countryWithFirstSpaceflight
http://dbpedia.org/ontology/county
http://dbpedia.org/ontology/coverArtist
http://dbpedia.org/ontology/creativeDirector
http://dbpedia.org/ontology/creator
http://dbpedia.org/ontology/crew
http://dbpedia.org/ontology/crewMember
http://dbpedia.org/ontology/crosses
http://dbpedia.org/ontology/currentMember
http://dbpedia.org/ontology/currentPartner
http://dbpedia.org/ontology/currentTeam
http://dbpedia.org/ontology/custodian
http://dbpedia.org/ontology/dean
http://dbpedia.org/ontology/deathCause
http://dbpedia.org/ontology/deathPlace
http://dbpedia.org/ontology/debutTeam
http://dbpedia.org/ontology/denomination
http://dbpedia.org/ontology/department
http://dbpedia.org/ontology/derivative
http://dbpedia.org/ontology/designer
http://dbpedia.org/ontology/destination
http://dbpedia.org/ontology/developer
http://dbpedia.org/ontology/director
http://dbpedia.org/ontology/discoverer
http://dbpedia.org/ontology/distributingCompany
http://dbpedia.org/ontology/distributingLabel
http://dbpedia.org/ontology/distributor
http://dbpedia.org/ontology/district
http://dbpedia.org/ontology/division
http://dbpedia.org/ontology/doctoralAdvisor
http://dbpedia.org/ontology/doctoralStudent
http://dbpedia.org/ontology/domain
http://dbpedia.org/ontology/draftTeam
http://dbpedia.org/ontology/drainsFrom
http://dbpedia.org/ontology/drainsTo
http://dbpedia.org/ontology/editing
http://dbpedia.org/ontology/editor
http://dbpedia.org/ontology/education
http://dbpedia.org/ontology/emmyAward
http://dbpedia.org/ontology/employer
http://dbpedia.org/ontology/endPoint
http://dbpedia.org/ontology/endingTheme
http://dbpedia.org/ontology/engine
http://dbpedia.org/ontology/engineer
http://dbpedia.org/ontology/ethnicGroup
http://dbpedia.org/ontology/ethnicity
http://dbpedia.org/ontology/event
http://dbpedia.org/ontology/executiveHeadteacher
http://dbpedia.org/ontology/executiveProducer
http://dbpedia.org/ontology/family
http://dbpedia.org/ontology/fastestDriver
http://dbpedia.org/ontology/fastestDriverCountry
http://dbpedia.org/ontology/fastestDriverTeam
http://dbpedia.org/ontology/father
http://dbpedia.org/ontology/federalState
http://dbpedia.org/ontology/field
http://dbpedia.org/ontology/film
http://dbpedia.org/ontology/filmFareAward
http://dbpedia.org/ontology/firstDriver
http://dbpedia.org/ontology/firstDriverCountry
http://dbpedia.org/ontology/firstDriverTeam
http://dbpedia.org/ontology/firstFlight
http://dbpedia.org/ontology/firstLaunchRocket
http://dbpedia.org/ontology/firstRace
http://dbpedia.org/ontology/firstWin
http://dbpedia.org/ontology/firstWinner
http://dbpedia.org/ontology/flagBearer
http://dbpedia.org/ontology/followingEvent
http://dbpedia.org/ontology/format
http://dbpedia.org/ontology/formerChoreographer
http://dbpedia.org/ontology/formerCoach
http://dbpedia.org/ontology/formerHighschool
http://dbpedia.org/ontology/formerPartner
http://dbpedia.org/ontology/formerTeam
http://dbpedia.org/ontology/foundationOrganisation
http://dbpedia.org/ontology/foundationPerson
http://dbpedia.org/ontology/foundationPlace
http://dbpedia.org/ontology/foundingPerson
http://dbpedia.org/ontology/frazioni
http://dbpedia.org/ontology/fuelSystem
http://dbpedia.org/ontology/fuelType
http://dbpedia.org/ontology/garrison
http://dbpedia.org/ontology/geminiAward
http://dbpedia.org/ontology/generalManager
http://dbpedia.org/ontology/genre
http://dbpedia.org/ontology/genus
http://dbpedia.org/ontology/goldenCalfAward
http://dbpedia.org/ontology/goldenGlobeAward
http://dbpedia.org/ontology/goldenRaspberryAward
http://dbpedia.org/ontology/governmentType
http://dbpedia.org/ontology/goyaAward
http://dbpedia.org/ontology/grammyAward
http://dbpedia.org/ontology/ground
http://dbpedia.org/ontology/growingGrape
http://dbpedia.org/ontology/guest
http://dbpedia.org/ontology/hasJunctionWith
http://dbpedia.org/ontology/head
http://dbpedia.org/ontology/headAlloy
http://dbpedia.org/ontology/headquarter
http://dbpedia.org/ontology/headquarters
http://dbpedia.org/ontology/headteacher
http://dbpedia.org/ontology/heir
http://dbpedia.org/ontology/highschool
http://dbpedia.org/ontology/homeTown
http://dbpedia.org/ontology/hometown
http://dbpedia.org/ontology/honours
http://dbpedia.org/ontology/house
http://dbpedia.org/ontology/hubAirport
http://dbpedia.org/ontology/iftaAward
http://dbpedia.org/ontology/illustrator
http://dbpedia.org/ontology/industry
http://dbpedia.org/ontology/inflow
http://dbpedia.org/ontology/influenced
http://dbpedia.org/ontology/influencedBy
http://dbpedia.org/ontology/innervates
http://dbpedia.org/ontology/instrument
http://dbpedia.org/ontology/isPartOf
http://dbpedia.org/ontology/island
http://dbpedia.org/ontology/jointCommunity
http://dbpedia.org/ontology/keyPerson
http://dbpedia.org/ontology/kingdom
http://dbpedia.org/ontology/knownFor
http://dbpedia.org/ontology/label
http://dbpedia.org/ontology/landingvehicle
http://dbpedia.org/ontology/language
http://dbpedia.org/ontology/languageType
http://dbpedia.org/ontology/largestCity
http://dbpedia.org/ontology/largestMetro
http://dbpedia.org/ontology/largestSettlement
http://dbpedia.org/ontology/largestSettlementType
http://dbpedia.org/ontology/lastFlight
http://dbpedia.org/ontology/lastLaunchRocket
http://dbpedia.org/ontology/lastRace
http://dbpedia.org/ontology/lastWin
http://dbpedia.org/ontology/launchPad
http://dbpedia.org/ontology/launchSite
http://dbpedia.org/ontology/launchvehicle
http://dbpedia.org/ontology/laurenceOlivierAward
http://dbpedia.org/ontology/layout
http://dbpedia.org/ontology/leader
http://dbpedia.org/ontology/leaderName
http://dbpedia.org/ontology/leaderParty
http://dbpedia.org/ontology/league
http://dbpedia.org/ontology/license
http://dbpedia.org/ontology/locatedInArea
http://dbpedia.org/ontology/location
http://dbpedia.org/ontology/locationCity
http://dbpedia.org/ontology/locationCountry
http://dbpedia.org/ontology/lounge
http://dbpedia.org/ontology/lunarRover
http://dbpedia.org/ontology/lymph
http://dbpedia.org/ontology/lyrics
http://dbpedia.org/ontology/maidenFlightRocket
http://dbpedia.org/ontology/majorIsland
http://dbpedia.org/ontology/majorShrine
http://dbpedia.org/ontology/management
http://dbpedia.org/ontology/manager
http://dbpedia.org/ontology/managerClub
http://dbpedia.org/ontology/managingEditor
http://dbpedia.org/ontology/manufacturer
http://dbpedia.org/ontology/march
http://dbpedia.org/ontology/mediaType
http://dbpedia.org/ontology/meetingBuilding
http://dbpedia.org/ontology/meetingCity
http://dbpedia.org/ontology/memberOfParliament
http://dbpedia.org/ontology/militaryRank
http://dbpedia.org/ontology/mission
http://dbpedia.org/ontology/mostWinner
http://dbpedia.org/ontology/mother
http://dbpedia.org/ontology/mouth
http://dbpedia.org/ontology/mouthCountry
http://dbpedia.org/ontology/mouthDistrict
http://dbpedia.org/ontology/mouthMountain
http://dbpedia.org/ontology/mouthPlace
http://dbpedia.org/ontology/mouthRegion
http://dbpedia.org/ontology/mouthState
http://dbpedia.org/ontology/movement
http://dbpedia.org/ontology/music
http://dbpedia.org/ontology/musicBy
http://dbpedia.org/ontology/musicFusionGenre
http://dbpedia.org/ontology/musicSubgenre
http://dbpedia.org/ontology/musicalArtist
http://dbpedia.org/ontology/musicalBand
http://dbpedia.org/ontology/naacpImageAward
http://dbpedia.org/ontology/namedAfter
http://dbpedia.org/ontology/narrator
http://dbpedia.org/ontology/nationalFilmAward
http://dbpedia.org/ontology/nationalOlympicCommittee
http://dbpedia.org/ontology/nationalOrigin
http://dbpedia.org/ontology/nationalTeam
http://dbpedia.org/ontology/nationality
http://dbpedia.org/ontology/nearestCity
http://dbpedia.org/ontology/neighboringMunicipality
http://dbpedia.org/ontology/nerve
http://dbpedia.org/ontology/network
http://dbpedia.org/ontology/nextMission
http://dbpedia.org/ontology/nobelLaureates
http://dbpedia.org/ontology/notableCommander
http://dbpedia.org/ontology/notableStudent
http://dbpedia.org/ontology/notableWine
http://dbpedia.org/ontology/notableWork
http://dbpedia.org/ontology/occupation
http://dbpedia.org/ontology/officerInCharge
http://dbpedia.org/ontology/officialOpenedBy
http://dbpedia.org/ontology/oilSystem
http://dbpedia.org/ontology/olivierAward
http://dbpedia.org/ontology/olympicOathSwornByAthlete
http://dbpedia.org/ontology/olympicOathSwornByJudge
http://dbpedia.org/ontology/openingFilm
http://dbpedia.org/ontology/openingTheme
http://dbpedia.org/ontology/operatingSystem
http://dbpedia.org/ontology/operator
http://dbpedia.org/ontology/order
http://dbpedia.org/ontology/organisation
http://dbpedia.org/ontology/origin
http://dbpedia.org/ontology/originalEndPoint
http://dbpedia.org/ontology/originalStartPoint
http://dbpedia.org/ontology/otherAppearances
http://dbpedia.org/ontology/otherParty
http://dbpedia.org/ontology/outflow
http://dbpedia.org/ontology/owner
http://dbpedia.org/ontology/owningCompany
http://dbpedia.org/ontology/owningOrganisation
http://dbpedia.org/ontology/parent
http://dbpedia.org/ontology/parentCompany
http://dbpedia.org/ontology/partOf
http://dbpedia.org/ontology/partOfWineRegion
http://dbpedia.org/ontology/partner
http://dbpedia.org/ontology/party
http://dbpedia.org/ontology/pastMember
http://dbpedia.org/ontology/pastTeam
http://dbpedia.org/ontology/patron
http://dbpedia.org/ontology/peabodyAward
http://dbpedia.org/ontology/photographer
http://dbpedia.org/ontology/phylum
http://dbpedia.org/ontology/place
http://dbpedia.org/ontology/placeOfBurial
http://dbpedia.org/ontology/placeOfOrigin
http://dbpedia.org/ontology/platform
http://dbpedia.org/ontology/poleDriver
http://dbpedia.org/ontology/poleDriverCountry
http://dbpedia.org/ontology/poleDriverTeam
http://dbpedia.org/ontology/populationPlace
http://dbpedia.org/ontology/port1
http://dbpedia.org/ontology/port2
http://dbpedia.org/ontology/precursor
http://dbpedia.org/ontology/predecessor
http://dbpedia.org/ontology/presenter
http://dbpedia.org/ontology/president
http://dbpedia.org/ontology/previousEditor
http://dbpedia.org/ontology/previousEvent
http://dbpedia.org/ontology/previousInfrastructure
http://dbpedia.org/ontology/previousMission
http://dbpedia.org/ontology/previousWork
http://dbpedia.org/ontology/principal
http://dbpedia.org/ontology/principalEngineer
http://dbpedia.org/ontology/producer
http://dbpedia.org/ontology/product
http://dbpedia.org/ontology/programmingLanguage
http://dbpedia.org/ontology/promotion
http://dbpedia.org/ontology/prospectTeam
http://dbpedia.org/ontology/province
http://dbpedia.org/ontology/provost
http://dbpedia.org/ontology/publisher
http://dbpedia.org/ontology/recentWinner
http://dbpedia.org/ontology/recordPlace
http://dbpedia.org/ontology/rector
http://dbpedia.org/ontology/region
http://dbpedia.org/ontology/region1
http://dbpedia.org/ontology/regionalLanguage
http://dbpedia.org/ontology/related
http://dbpedia.org/ontology/relatedAutomobile
http://dbpedia.org/ontology/relatedAutomobilePlatform
http://dbpedia.org/ontology/relation
http://dbpedia.org/ontology/relative
http://dbpedia.org/ontology/religion
http://dbpedia.org/ontology/residence
http://dbpedia.org/ontology/resides
http://dbpedia.org/ontology/restingPlace
http://dbpedia.org/ontology/retiredRocket
http://dbpedia.org/ontology/rival
http://dbpedia.org/ontology/rocket
http://dbpedia.org/ontology/royalAnthem
http://dbpedia.org/ontology/ruralMunicipality
http://dbpedia.org/ontology/saint
http://dbpedia.org/ontology/school
http://dbpedia.org/ontology/screenActorsGuildAward
http://dbpedia.org/ontology/secondCommander
http://dbpedia.org/ontology/secondDriver
http://dbpedia.org/ontology/secondDriverCountry
http://dbpedia.org/ontology/secondTeam
http://dbpedia.org/ontology/selection
http://dbpedia.org/ontology/series
http://dbpedia.org/ontology/service
http://dbpedia.org/ontology/show
http://dbpedia.org/ontology/shuttle
http://dbpedia.org/ontology/significantBuilding
http://dbpedia.org/ontology/significantDesign
http://dbpedia.org/ontology/significantProject
http://dbpedia.org/ontology/similar
http://dbpedia.org/ontology/sisterCollege
http://dbpedia.org/ontology/sisterNewspaper
http://dbpedia.org/ontology/sisterStation
http://dbpedia.org/ontology/skatingClub
http://dbpedia.org/ontology/sourceCountry
http://dbpedia.org/ontology/sourceDistrict
http://dbpedia.org/ontology/sourceMountain
http://dbpedia.org/ontology/sourcePlace
http://dbpedia.org/ontology/sourceRegion
http://dbpedia.org/ontology/sourceState
http://dbpedia.org/ontology/spacecraft
http://dbpedia.org/ontology/species
http://dbpedia.org/ontology/sport
http://dbpedia.org/ontology/spouse
http://dbpedia.org/ontology/spurType
http://dbpedia.org/ontology/starring
http://dbpedia.org/ontology/startPoint
http://dbpedia.org/ontology/state
http://dbpedia.org/ontology/states
http://dbpedia.org/ontology/station
http://dbpedia.org/ontology/statisticLabel
http://dbpedia.org/ontology/storyEditor
http://dbpedia.org/ontology/structuralSystem
http://dbpedia.org/ontology/stylisticOrigin
http://dbpedia.org/ontology/subject
http://dbpedia.org/ontology/subregion
http://dbpedia.org/ontology/subsequentInfrastructure
http://dbpedia.org/ontology/subsequentWork
http://dbpedia.org/ontology/subsidiary
http://dbpedia.org/ontology/successor
http://dbpedia.org/ontology/summerAppearances
http://dbpedia.org/ontology/superintendent
http://dbpedia.org/ontology/supplies
http://dbpedia.org/ontology/system
http://dbpedia.org/ontology/targetAirport
http://dbpedia.org/ontology/team
http://dbpedia.org/ontology/teamOwner
http://dbpedia.org/ontology/teamPresident
http://dbpedia.org/ontology/tenant
http://dbpedia.org/ontology/territory
http://dbpedia.org/ontology/thirdCommander
http://dbpedia.org/ontology/thirdDriver
http://dbpedia.org/ontology/thirdDriverCountry
http://dbpedia.org/ontology/thirdTeam
http://dbpedia.org/ontology/thumbnail
http://dbpedia.org/ontology/tonyAward
http://dbpedia.org/ontology/torchBearer
http://dbpedia.org/ontology/trainer
http://dbpedia.org/ontology/training
http://dbpedia.org/ontology/translator
http://dbpedia.org/ontology/trustee
http://dbpedia.org/ontology/twinCity
http://dbpedia.org/ontology/twinCountry
http://dbpedia.org/ontology/type
http://dbpedia.org/ontology/unit
http://dbpedia.org/ontology/university
http://dbpedia.org/ontology/usingcountry
http://dbpedia.org/ontology/valvetrain
http://dbpedia.org/ontology/variant
http://dbpedia.org/ontology/varietals
http://dbpedia.org/ontology/vehicle
http://dbpedia.org/ontology/vein
http://dbpedia.org/ontology/veneratedIn
http://dbpedia.org/ontology/viceChancellor
http://dbpedia.org/ontology/vicePresident
http://dbpedia.org/ontology/vicePrincipal
http://dbpedia.org/ontology/voice
http://dbpedia.org/ontology/voiceType
http://dbpedia.org/ontology/wars
http://dbpedia.org/ontology/whaDraftTeam
http://dbpedia.org/ontology/wineProduced
http://dbpedia.org/ontology/wineRegion
http://dbpedia.org/ontology/winterAppearances
http://dbpedia.org/ontology/writer
http://dbpedia.org/ontology/youthClub
*/
}