<?php
require_once(dirname(__FILE__)."./var.php");
require_once(dirname(__FILE__)."./lib.php");

global $lang;

$search = urlencode($_GET["sitesearch"])."+site:$searchsite";

$url = "http://boss.yahooapis.com/ysearch/web/v1/";
$urlrest = "?appid=".$yahoo_app_id."&format=xml&abstract=long";
if (isset($_GET["start"])) {$urlrest .= "&start=".$_GET["start"];}
if (isset($_GET["count"])) {$urlrest .= "&count=".$_GET["count"];}

$finalurl = $url.$search.$urlrest;
//echo $finalurl;

$str =  fetch_url($finalurl) ;
$xml = simplexml_load_string($str);

$totalhits = $xml->resultset_web['totalhits'];
$starthit = $xml->resultset_web['start'];
$steps = 10;
$stephit = $xml->resultset_web['count'];
$prevhit = $starthit-$stephit;
$nexthit = $starthit+$stephit;

if ($lang == 'pt') {
	echo "<DIV class='search_results_summary'>Pesquisa por \"<I>".$search."</i>\" obteve ".$totalhits." resultados. ";
	if ($totalhits != 0) {echo "Apresentando os resultados ".($starthit+1)." a $nexthit.\n"; 
	echo "</DIV>\n";
}
if ($lang == 'en') {
	echo "<DIV class='search_results_summary'>Your search for \"<I>".$search."</i>\" got ".$totalhits." results. ";
if ($totalhits != 0) {echo "Showing results ".($starthit+1)." to $nexthit.\n";}
	echo "</DIV>\n";
}

foreach ($xml->resultset_web->result as $result) {

 echo '<P><div class="search_results_link"><B><a href="'.$result->clickurl.'">'.$result->title.'</a></B></div>';
 echo '<div class="search_results_abstract">'.$result->abstract.'</div>';
 echo '<div class="search_results_url">'.$result->url.' - '.(intval($result->size/1000.0)).'KB - '.$result->date.'</div></P>';
} 

  echo "<div align='center'>";
  if ($starthit != 0) {
  	echo "<a href=\"".curPageURL(array('start'=>$prevhit))."\">";
	echo $buttons['prev'][$lang].'</a>';
  }
   // max pages to show 
  $currentpage = intval(($starthit+$steps) / $steps);
  $max = (intval(($totalhits+$steps) / $steps)) > 10 ? 10 : intval(($totalhits+$steps) / $steps);
   // Which page am I in?
  
   for ($i=1; $i < $max; $i++) {
		echo " ";
		if ($i != $currentpage) {
			$targetedhit = ($i-1)*$steps;
			echo '<a href="'.curPageURL(array('start'=>$targetedhit)).'">';
		}
		echo $i;
		if ($i != $currentpage) {echo "</a>";}
   	}
   	if (!($nexthit >= $totalhits)) {
		echo " <a href=\"".curPageURL(array('start'=>$nexthit))."\"> ";
		echo $buttons['next'][$lang]."</a>";
	}
}

if ($lang == 'pt') echo "<P>Resultados gerados pelo <a href=\"http://developer.yahoo.com/search/boss/\">Yahoo! BOSS</a>.</P>\n";
if ($lang == 'en') echo "<P>Results generated by <a href=\"http://developer.yahoo.com/search/boss/\">Yahoo! BOSS</a>.</P>\n";
echo "</DIV>\n";
?>