<H3>REMBRANDT's documentation: API and source code</H3>

<P>The <a href="<?php echo $urlbasedir."/".$apidir."/".$rembrandtLatestVersion; ?>">REMBRANDT's API</A> for its latest release (version <?php echo $rembrandtLatestVersion;?>) in JavaDoc (generated by <a href="http://www.javalobby.org/java/forums/t102917.html">GroovyDoc</a>) is also included on the REMBRANDT package.</P>

<P>The REMBRANDT source code, which is also included in the REMBRANDT package, can be browsed through the <A HREF="<?php echo $rembrandtGoogleCodeURL; ?>">Rembrandt's Google Code site</A>. But before that, I recommend that you get acquainted with the <a href="http://groovy.codehaus.org">Groovy programming language</a>. Don't be scared: think of Groovy as Java with a cleaner and friendlier syntax for humans.</P>	

<iframe width="100%" height="400" src="http://code.google.com/p/rembrandt/source/browse/"></iframe>	
