/** This file is part of REMBRANDT - Named Entity Recognition Software
 *  (http://xldb.di.fc.ul.pt/Rembrandt)
 *  Copyright (c) 2008-2009, Nuno Cardoso, University of Lisboa and Linguateca.
 *
 *  REMBRANDT is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  REMBRANDT is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with REMBRANDT. If not, see <http://www.gnu.org/licenses/>.
 */
 
package saskia.gazetteers

import rembrandt.obj.Term
import rembrandt.obj.Sentence
import rembrandt.rules.MatcherObject
/**
 * @author Nuno Cardoso
 * bom para saber, a partir de uma expressão, qual a classe DBpedia que quero.
 * Categorias Wikipédia podem ser vistas como expressões, porque não? Mas há melhores formas de fazer...
 * com a sua ontologia.
 * This class mustn't be saved in UTF-8
 */
class DBpediaOntology32Definitions extends DBpediaOntologyDefinitions {
    
 //   static MatcherObject mo = new MatcherObject()
    
   /* static getAnswerFromNeedle(Sentence query) {
	  return mo.meaningMatch(query, definitions)
    }*/
		
	// use arrays for OR semantics, otherwise read as AND semantics	
	
   static definitions = [
	[answer:"Actor", plain:[en:[["Actors"],["Actresses"]], pt:[["Actores"],["Actrizes"]]], 
		needle:[en:[[~/[Aa]ctors?/], [~/[Aa]ctress(?:es)?/]], pt:[[~/[Aa]c?tor(es)?/], [~/[Aa]c?triz(es)?/]] ] ],
	[answer:"AdultActor", plain:[],
	    needle:[en:[[~/[Aa]c?tors?/], [~/[Aa]ctress(?:es)?/]], pt:[[~/[Aa]c?tor(es)?/], [~/[Aa]c?triz(es)?/]] ] ],
	[answer:"Aircraft",  plain:[en:[["Aircrafts"],["Airplanes"]], pt:"Aviões"],
	  	needle:[en:~/[Aa]ir(?:craft|plane)s?/, pt:~/[Aa]vi(ão|ões)/ ] ],
	[answer:"Airline", plain:[en:"Airlines", pt:["Companhias","aéreas"] ],
	 	needle:[en:~/[Aa]irlines?/, pt:[ [~/[Ee]mpresas/,~/[Aa]éreas?/], [~/[Cc]ompanhias?/,~/[Aa]éreas?/] ] ] ],
	[answer:"Airport", plain:[en:"Airports", pt:"Aeroportos"],
		needle:[en:~/[Aa]irports?/, pt:[ [~/[Aa]eroportos?/],[~/[Aa]er[óô]dromos?/] ] ] ],
	[answer:"Album", plain:[en:"Albuns", pt:"Álbuns"], 
		needle:[en:~/[Aa]lbu[mn]s?/, pt:~/[áÁ]lbu[mn]s?/] ],
	[answer:"AnatomicalStructure", plain:[], neddle:[] ]	,
	[answer:"Animal", plain:[en:"Animals", pt:"Animais"], 
		needle:[en:~/[Aa]nimals?/, pt:~/[Aa]nima[li]s?/] ],
	[answer:"Architect", plain:[en:"Architects", pt:"Arquitectos"], 
		needle:[en:~/[Aa]rchitects?/, pt:~/[Aa]rquitec?t[oa]s/] ],
	[answer:"Area", plain:[en:"Area", pt:"Área"], 
		needle:[en:[[~/[Cc]ontinents?/], [~/[Ss]tates/], [~/[Rr]egions?/], ['NUTS?',~/I*/] ], 
		      pt:[ [~/[Cc]ontinentes?/], [~/[Ee]stados/], [~/[Cc]lassificação/,'dos',~/[Pp]aíses/], 
		      [~/[Gg]randes?/,~/[Áá]reas/, /[Mm]etropolitanas?/],
			  [~/[Rr]egi(ão|ões)/],[~/NUTS?/,~/I*/] ]  ] ], 
	[answer:"Artery", plain:[en:"Arteries", pt:"Artérias"], 
		needle:[en:~/[Aa]rter(?:y|ies)/, pt:~/[Aa]rtérias?/] ],
	[answer:"Artist", plain:[en:"Artists", pt:"Artistas"], 
		needle: [en:[[~/[Aa]uthors?/], [~/[Pp]resenters?/], [~/[Aa]rtists?/], [~/[Cc]eramists?/], 
	  			[~/[Dd]ancers?/], [~/[Ss]culptors?/],[~/[Pp]hotographers?/], [~/[Pp]ainters?/], 
      			[~/[Dd]irectors?/],[~/[Pp]oets?/]], 
				pt:[[~/[Aa]utor[ae]?s?/], [~/[Aa]presentador[ea]?s?/],
	  			[~/[Aa]rtistas?/], [~/[Cc]eramistas?/], [~/[Cc]ineastas?/], [~/[Cc]inegrafistas?/], 
	  			[~/[Dd]ançarinos?/], [~/[Ee]scultor[ae]?s?/],[~/[Ff]otógrafos?/], [~/[Pp]intor[ae]?s?/], 
      			[~/[Rr]ealizador[ae]s?/],[~/[Pp]oetas?/] ] ] ],
	[answer:"Astronaut", plain:[en:"Astronauts",pt:"Astronautas"], 
		needle:[en:~/[Aa]stronauts?/, pt:~/[Aa]stronautas?/] ],
	[answer:"Athlete", plain:[en:"Athletes", pt:"Atletas"], 
		needle:[en:[[~/[Aa]thletes?/], [~/[Rr]eferees?/], [~/[Ss]portsm[ae]n/], [~/[Pp]layers?/] ],
		   pt:[[ ~/[Aa]lpinistas?/], [~/[Aa]tletas?/], 
	  [~/[Áá]rbitros?/], [~/[Dd]esportistas?/], [~/[Jj]ogador[ea]s?/], [~/[Jj]udocas?/] ] ] ],
	[answer:"Automobile",plain:[en:[["Car"],["Automobile"]], pt:[['Carros'],['Automóveis']]],
	  needle:[en:[[~/[Cc]ars?/],[~/[Aa]utomobiles?/]], 
	       pt:[[~/[Vv]eículos?/],[~/[Cc]arros?/], [~/[Aa]utomóve[il]s?/]] ] ],
	[answer:"Archaea", plain:[], needle:[]],
	[answer:"Bacteria", plain:[en:"Bacterias", pt:"Bactérias"], 
		needle:[en:~/[Bb]acterias?/, pt:~/[Bb]actérias?/] ]	,
	[answer:"BadmintonPlayer", plain:[en:["Badminton","Player"], pt:["Jogadores","de","Badminton"]],
	    needle:[en:[~/[Bb]adminton/, ~/[Pp]layers?/], pt:[~/[Jj]ogador(?:es)?/,'de', ~/[Bb]adminton/] ] ],		,
	[answer:"BaseballPlayer", plain:["Baseball Player"], 
	    needle:[[~/[Bb]aseball','[Pp]layers?/]] ],
	[answer:"BasketballPlayer", plain:["Basketball Player"], 
	 	needle:[[~/[Bb]asketball','[Pp]layers?/]] ],
	[answer:"Beverage", plain:["Beverages"], needle:[[~/[Bb]everages?/],[~/[Cc]ocktails?/],[~/[Dd]rinks?/]] ],
	[answer:"Bone", plain:["Bones"], needle:[[~/[Bb]ones?/]] ],
	[answer:"Book", plain:["Books"], needle:[[~/[Bb]ooks?/], [~/[Mm]anuscripts?/]] ],
	[answer:"Boxer", plain:["Boxers"], needle:[[~/[Bb]oxers?/]] ]      ,
	[answer:"Brain", plain:["Brains"], needle:[[~/[Bb]rains?/]] ],
	[answer:"Bridge", plain:["Bridges"], needle:[[~/[Bb]ridges?/]] ],
	[answer:"BritishRoyalty", plain:["British Royalty"], needle:[[~/[Ll]ords?/],[~/[Dd]ukes?/],[~/[Dd]uchess(?:es)?/]] ],
	[answer:"Broadcast", plain:["Broadcasts"], needle:[['TV',~/[Pp]rograms?/]] ] ,
	[answer:"Building", plain:["Buildings"], needle:[[~/[Cc]onstructions?/], 
	[~/[Cc]athedrals?/], [~/[Cc]inemas?/], [~/[Cc]onvents?/], [~/[Cc]hurches?/], 
	[~/[Mm]useums?/], [~/[Mm]onastar(?:y|ies)/], [~/[Pp]orts?/], 
	[~/[Tt]heat(?:re|er)s?/], [~/[Tt]owers?/]] ],
	[answer:"Band", plain:["Bands"], needle:[[~/[Bb]ands?/]] ],
	[answer:"Cardinal", plain:["Cardinals"], needle:[[~/[Cc]ardinals?/]] ],
	[answer:"Cave", plain:["Caves"], needle:[[~/[Cc]aves?/]]],
	[answer:"ChemicalCompound", plain:["Chemical Compounds"], 
	 	needle:[ [~/[Cc]hemical/,~/[Cc]ompounds?/] ]],
	[answer:"ChristianBishop", plain:["Bishops"], needle:[[~/[Bb]ishops?/]] ],
	[answer:"City", plain:["Cities","Towns"],  needle:[[~/[Cc]apitals?/],[~/[Cc]it(?:y|ies)/],
      [~/[Tt]owns?/], [~/[Ll]ocalit(?:y|ies)/],[~/[Vv]illages?/]] ],
	[answer:"Cleric", plain:["Cleric","Clerk"], needle:[[~/[Pp]riests?/]] ],
	[answer:"College", plain:["Colleges"], needle:[[~/[Cc]olleges?/]] ],
	[answer:"CollegeCoach", plain:["College Coach"], needle:[[]] ],
	[answer:"Comedian", plain:["Comediants"], needle:[[~/[Cc]omediants?/],[~/[Hh]umourists?/]] ],
	[answer:"ComicsCharacter", plain:["Comics Characters"], needle:[[~/[Cc]omics?/,~/[Cc]haracters?/]] ],
	[answer:"ComicsCreator", plain:["Comics Creators"], needle:[[~/[Cc]omics?/,~/[Cc]reators?/],
	 [~/[Ii]llustrators?/]] ],
	[answer:"Company", plain:["Companies"], needle:[[~/[Cc]ompan(?:y|ies)/],[~/[Cc]orporations?/]] ],
	[answer:"Convention", plain:["Conventions","Conferences"], needle:[[~/[Cc]onventions?/],[~/[Cc]onferences?/]] ],
	[answer:"Country", plain:["Countries"], needle:[[~/[Cc]ountr(?:y|ies)?/],[~/[Dd]emocracies?/],
	[~/[Rr]epublics?/],[~/[Kk]ingdoms?/],[~/[Ee]mirates?/],[~/[Nn]ations?/]]  ] ,
	[answer:"Cricketer", plain:["Cricketers"], needle:[[~/[Cc]ricketers?/]] ],
	[answer:"Criminal", plain:["Criminals"], needle:[[~/[Cc]riminals?/]] ],
	[answer:"Currency",  plain:["Currencies"], needle:[[~/[Cc]urrenc(?:y|ies)/]] ],
	[answer:"Cyclist",  plain:["Cyclists"], needle:[[~/[Cc]yclists?/]] ],
	[answer:"Celebrity", plain:["Celebrities"], needle:[[~/[Cc]elebrit(?:y|ies)/]] ],
	[answer:"Congressman", plain:["Congressmen"], needle:[[~/[Cc]ongressm[ae]n/],[~/[Cc]ongresswomans?/]] ] ,
	[answer:"Chancellor", plain:["Chancellors"], needle:[[~/[Cc]hancellors?/]] ],
	[answer:"Disease", plain:["Diseases"], needle:[[~/[Dd]iseases?/], [~/[Dd]eformations?/], [~/[Ss]yndroms?/]] ] ,
	[answer:"Drug", plain:["Drugs"], needle:[[~/[Dd]rugs?/]] ],
	[answer:"EducationalInstitution", plain:["Educational Institution"], needle:[[]]],
	[answer:"Embryology", plain:[], needle:[[]]],
	[answer:"EthnicGroup", plain:["Ethnic Groups"], needle:[[]] ],
	[answer:"EurovisionSongContestEntry", plain:[], needle:[[]]],
	[answer:"Event", plain:["Events"], needle:[[~/[Ee]vents?/]] ],
	[answer:"Eukaryote", plain:[], needle:[[]]],
	[answer:"FictionalCharacter", plain:['Fictional Characters'], needle:[[~/[Ff]ictional','[Cc]haracters?/]] ] ,
	[answer:"FigureSkater", plain:["Figure Skaters"], needle:[[~/[Ff]igure','[Ss]katers?/]] ],
	[answer:"Film", plain:["Films","Movies"], needle:[[~/[Ff]ilme?/],["[Mm]ovies?"]] ],
	[answer:"FilmFestival", plain:["Film Festival","Movie Festival"], needle:[[~/[Ff]ilm/, ~/[Ff]estivals?/],[~/[Mm]ovie/, ~/[Ff]estivals?/]] ],
	[answer:"FootballPlayer", plain:["Football Players"], needle:[[~/[Ff]ootball/,~/[Pp]layers?/]] ],
	[answer:"FootballTeam", plain:["Football Teams"], 
	 	needle:[[~/[FF]ootabll/, ~/[Tt]eams?/],[~/[Ff]ootball/, ~/[Cc]lubs?/]] ],
	[answer:"FormulaOneRacer", plain:["Formula One Racer"], needle:[[~/[Pp]ilots?/],[~/[Ff]ormula/,~/[Oo]ne/,~/[Rr]acers?/]] ],
	[answer:"Fungus", plain:["Fungus"], needle:[[~/[Ff]ungus?/]]],
	[answer:"FootballManager", plain:["Football Manager"], 
	 	needle:[[~/[Ff]ootball/, ~/[Mm]anagers?/]] ],
	[answer:"GaelicGamesPlayer",  plain:[], needle:[[]]],
	[answer:"GrandPrix", plain:["Grand Prix"], needle:[[~/[Gg]rand/,~/[Pp]rix/]] ],
	[answer:"Grape", plain:["Grapes"], needle:[[~/[Gg]rapes?/]]],
	[answer:"Governor", plain:["Governors"], needle:[[ ~/[Gg]overnors?/]] ],
	[answer:"HistoricBuilding", plain:["Historic Buildings"],  
	 	needle:[[~/[Cc]astles?/],[~/[Ff]ortress(?:es)/],[~/[Mm]onuments?/], [~/[Pp]alaces?/]] ],
	[answer:"HistoricPlace", plain:["Historic Place"], needle:[[]]],
	[answer:"HockeyTeam", plain:["Hockey Teams?"],  neddle:[[~/[Hh]ockey/, ~/[TT]eams?/]] ],
	[answer:"Hospital", plain:["Hospitals"], needle: [[~/[Hh]ospitals?/]] ],
	[answer:"IceHockeyPlayer", plain:["Ice Hockey Players"], 
	 	needle:[[~/[Ii]ce/, ~/[Hh]ockey/, ~/[Pp]layers?/]] ],
	[answer:"Infrastructure", plain:[], needle:[[~/[Dd]ams?/]]],
	[answer:"Island", plain:["Islands", "Isles", "Archipelagos"], needle:[[~/[Aa]rchipelagos?/], [~/[Ii]slands?/], [~/[Ii]sles?/]] ],
	[answer:"Journalist", plain:["Journalists","Reporters"], needle:[[~/[Jj]ournalists?/],[~/[Rr]eporters?/]] ],
	[answer:"Judge", plain:["Judges"], neddle:[[~/[Aa]ttou?rneys?/], [~/[Jj]udges?/]] ],
	[answer:"Lake",  plain:["Lakes", "Seas", "Oceans"], needle:[[~/[Bb]ays?/], [~/[Cc]hannels?/], [~/[Gg]ulfs?/], 
         [~/[Ll]akes?/], [~/[Ll]ochs?/], [~/[Ss]eas?/], [~/[Oo]ceans?/]] ],
	[answer:"Language", plain:["Languages"], needle:[[~/[Ll]anguages?/],[~/[Dd]ialec?ts?/]] ],	
	[answer:"Legislature", plain:["Legislatures"], needle:[[~/[Ll]egislaturs?/]] ],
	[answer:"Lighthouse", plain:["Lighthouses"], needle:[[~/[Ll]ighthouses?/]] ] ,
	[answer:"LunarCrater", plain:["Lunar Craters"], needle:[[~/[Ll]unar/, ~/[Cc]raters?/]] ],
	[answer:"Lymph", plain:["Lymph"], needle:[[]]],
	[answer:"Magazine", plain:["Magazines"], needle:[[~/[Mm]agazines?/]] ],
	[answer:"MeanOfTransportation", plain:["Means of Transportation"], needle:[[~/[Rr]ockets?/]] ],
	[answer:"MilitaryConflict", plain:["Military Conflicts"], needle:[[~/[Bb]attles?/],[~/[Ww]ars?/], 
	    [~/[Rr]evolutions?/], [~/[Uu]prisings?/]] ],
	[answer:"MilitaryPerson", plain:["Military persons"],  needle:[[~/[Mm]ilitar(?:y_ies)/], 
        [~/[Cc]olonels?/], [~/[Gg]enerals?/], [~/[Mm]ajors?/]] ] ,
	[answer:"MilitaryUnit", plain:["Military Units"], needle:[[]]],
	[answer:"MixedMartialArtsEvent", plain:["Mixed Martial Arts Event"], needle:[[]]],
	[answer:"Model", plain:["Models"], needle:[[~/[Tt]op/, ~/[Mm]odels?/]] ],
	[answer:"Monarch", plain:["Monarchs","Kings","Queens"], needle:[[~/[Kk]ings?/], [~/[Qq]ueens?/], [~/[Rr]egents?/],
	    [~/[Pp]rinces?/],[~/[Pp]rincesses?/]] ] ,
	[answer:"Mountain", plain:["Mountains"],  needle:[
         [~/[Cc]anyons?/], [~/[Mm]ountains?/], [~/[Hh]ills?/],
        [~/[Pp]lains?/], [~/[Pp]lanalts?/], [~/[Pp]eaks?/], [~/[Ss]ierras?/], [~/[Vv]alleys?/] ] ] ,
	[answer:"Municipality", plain:["Municipalities"], needle:[[~/[Cc]omunes?/],[~/[Mm]unicipalit(?:y|ies)?/],
	    [~/[Pp]rovinces?/],[~/[Cc]ount(?:y|ies)/]] ],
	[answer:"Muscle", plain:["Muscles"], needle:[[~/[Mm]uscles?/]] ],
	[answer:"MusicFestival", plain:["Music Festivals"], needle:[[~/[Mm]usic/, ~/[Ff]estivals?/]] ],
	[answer:"MusicGenre", plain:["Music Genre"], needle:[[~/[Mm]usic/, ~/[Gg]enres?/]] ],
	[answer:"Musical", plain:["Musicals"], needle:[[~/[Mm]usicals/]] ],
	[answer:"MusicalArtist", plain:["Musical Artist"], needle:[[~/[Dd]rummers?/] , [~/[Bb]ass/, ~/[Pp]layers?/],
	    [~/[Ss]ingers?/],[~/[Gg]uitar/, ~/[Pp]layers?/],[~/[Cc]omposers?/], [~/[Mm]aestros?/],
	    [~/DJs?/],[~/[Mm]usicians?/], [~/[Oo]rchestrators?/]] ],
	[answer:"MusicalWork", plain:['Musical Work'], needle:[[]] ],
	[answer:"Monera", plain:["Monera"], needle:[[]] ],
	[answer:"MemberOfParliament", plain:["Members of Parliament"], needle:[[~/[Dd]eputees?/]] ],
	[answer:"Mayor", plain:["Mayors"], needle:[[~/[Mm]ayors?/]] ],
	[answer:"NascarDriver", plain:["NASCAR Driver"], needle:[["NASCAR","[Dd]rivers?"]] ],
	[answer:"NationalCollegiateAthleticAssociationAthlete", plain:[], needle:[[]] ],
	[answer:"Nerve", plain:["Nerves"], needle:[[~/[Nn]erv(?:es)?/]] ],
	[answer:"Newspaper", plain:["Newspapers"], needle:[[~/[Nn]ewspapers?/]] ],
	[answer:"Non-ProfitOrganisation", plain:["Institutions"], needle:[[~/[Aa]ssociations?/],
      [~/[Ii]nstitut(?:e|ion)s?/], [~/[Pp]olitical/, ~/[Pp]art(y|ies)/]] ],
	[answer:"OfficeHolder", plain:[], needle:[[]] ],
	[answer:"OlympicResult", plain:["Resultados olímpicos"], needle:[[]] ],
	[answer:"Olympics", plain:["Olympic Games"], needle:[[~/[Oo]lympic/, ~/[Gg]ames?/]] ],
	[answer:"Organisation", plain:["Organizations"], needle:[
	  [~/[Ss]patial/, ~/[Aa]genc(?:y|ies)/], [~/[Uu]nited/, ~/[Nn]ations?/], 
         [~/[Oo]rgani[sz]ations?/], [~/[Pp]arliaments?/], [~/[Ee]uropean/, ~/[Uu]nion/]] ] ,
	[answer:"Park", plain:["Parks"], needle:[[~/[Gg]reen/, ~/[Ss]paces?/], [~/[Gg]ardens?/], [~/[Pp]arks?/]] ],
	[answer:"Person", plain:["Persons"], needle:[[~/[Aa]viators?/], [~/[Bb]ankers?/], 
	  [~/[Ll]ibrarians?/],  [~/[Dd]irectors?/], [~/[Cc]ritics?/],
	  [~/[Ee]nterpreneurs?/], [~/[Ss]tylists?/], [~/[Ee]conomists?/], 
	  [~/[Ee]xplorers?/], [~/[Pp]hilantrophes?/], [~/[Hh]istoriers?/], 
	  [~/[Hh]umanists?/], [~/[Nn]avigators?/], [~/[Pp]rofessors?/], [~/[Tt]eachers?/], 
	  [~/[Pp]roducers?/],[~/[Pp]sychologists?/], [~/[Pp]sichiatrists?/],[~/[Rr]adialists?/], 
	  [~/[Ss]ociologists?/],  [~/[Tt]heologists?/], [~/[Tt]ypographs?/], 
	  [~/[Zz]oologists?/], [~/[Mm]anagers?/], 
	  [~/[Dd]iplomats?/], [~/[Ee]mperors?/]] ],
	[answer:"Philosopher", plain:["Philosophers"], needle:[[~/[Pp]h[iy]losophers?/]] ],
	[answer:"Place", plain:["Places"], needle:[
       [~/[Ss]traights?/], [~/[Ff]orests?/], [~/[Pp]laces?/]] ],
	[answer:"Planet", plain:["Planets"], needle:[
       [~/[Pp]lanets?/],[~/[Ss]tars?/], [~/[Ss]atellites?/], [~/[Cc]onstellations?/], 
       [~/[Ss]olar/, ~/[Ss]ystems?/]] ],
	[answer:"PlayboyPlaymate", plain:[], needle:[[]]],
	[answer:"PokerPlayer", plain:["Poker Players?"], needle:[[]]],
	[answer:"Politician", plain:["Polititians"], needle:[[~/[Pp]olititians?/], [~/[Mm]inisters?/]] ],
	[answer:"Pope", plain:["Popes"], needle:[[~/[Pp]opes?/]] ],
	[answer:"PopulatedPlace", plain:[], needle:[[]]],
	[answer:"ProtectedArea", plain:["Protected Areas"],  needle:[[]]],
	[answer:"Protein", plain:["Proteins"], needle:[[~/[Pp]roteins?/]] ],
	[answer:"Plant", plain:["Plants"], needle:[[~/[Pp]lants?/]] ],
	[answer:"Protista", plain:["Protista"], needle:[[]]],
	[answer:"President", plain:["Presidents"], needle:[[~/[Pp]residents?/]] ],
	[answer:"PrimeMinister", plain:["Prime-ministers", "Prime Ministers"], needle:[ [~/[Pp]rime-[Mm]inisters?/],
	   [~/[Pp]rime/, ~/[Mm]inisters?/], [~/[Pp]remi[eê]rs?/] ] ],
	[answer:"Race", plain:["Races"], needle:[[~/[Rr]aces?/]] ],
	[answer:"RadioStation", plain:["Radio stations"], needle:[[~/[Rr]adio/, ~/[Ss]tations?/]] ],
	[answer:"RecordLabel", plain:["Record Label"], needle:[[~/[Rr]ecord]/, ~/[Ll]abels?/]] ],
	[answer:"Resource", plain:[], needle:[[]]],
	[answer:"River", plain:["Rivers"], needle:[[~/[Ee]ffluents?/],[~/[Ww]aterfalls?/],
	   [~/[Rr]ivers?/], [~/[Ss]treams?/]] ],
	[answer:"Road", plain:["Roads","Streets","Highways","Freeways"], 
	   needle:[[~/[Hh]ighways?/], [~/[Aa]venues?/], 
	   [~/[Aa]lleys?/], [~/[Ss]treets?/],[~/[Ss]quares?/], 
	   [~/[Rr]oads?/], [~/[Hh]ighways/]] ] ,
	[answer:"RugbyPlayer", plain:["Rugby players"], needle:[[~/[Rr]ugby/, ~/[Pp]layers?/]] ],
	[answer:"Saint", plain:["Saints"], needle: [[~/[Aa]ngels?/], [~/[Dd]ivinit(?:y|ies)/],[~/[Ss]aints?/]] ],
	[answer:"School", plain:["Schools"], needle: [[~/[Ss]chools?/]] ],
	[answer:"Scientist", plain:["Scientists"], needle:[[~/[Aa]ntrophologists?/], [~/[Aa]stronomes?/],
	  [~/[Aa]rcheologists?/], [~/[Cc]artographs?/], [~/[Ss]cientists?/], [~/[Ll]inguists?/],
	  [~/[Ee]tnographs?/], [~/[Ee]ngineers?/],  [~/[Pp]hysics?/],
	  [~/[Ii]nventors?/], [~/[Mm]athematitians?/], [~/[Mm]edics?/], [~/[Dd]octors?/]] ],
	[answer:"ShoppingMall", plain:["Shopping malls"], needle:[[~/[Ss]hopping/,~/(?:[Cc]ent[re][re]s?|[Mm]alls?)/]] ],
	[answer:"Single", plain:[], needle:[[]] ],
	[answer:"SiteOfSpecialScientificInterest", plain:[], needle:[[]] ],
	[answer:"SkiArea", plain:["Ski Area"], needle:[[~/[Ss]ki/, ~/[Aa]reas?/]] ],
	[answer:"Skyscraper", plain:["Skyscrapers"], needle:[[~/[Ss]kyscrapers?/]] ],
	[answer:"SoccerClub", plain:["Soccer clubs"], needle:[[~/[Ss]occer/, ~/[Cc]lubs?/]] ],
	[answer:"Software", plain:["Programas"], needle:[[~/[Ee]mulator?/], [~/[Ss]oftwares?/]] ],
	[answer:"Song", plain:["Songs"], needle:[[~/[Ss]ongs?/]] ],
	[answer:"Species", plain:["Species"], needle:[[~/[Ss]pecies?/]] ],
	[answer:"SportsEvent", plain:["Sports events"], needle:[[~/[Ss]ports?/, ~/[Ee]vents?/], 
	  [~/[Cc]hampionships?/]] ],
	[answer:"SportsTeam", plain:["Sports Teams"], needle:[[~/[Ss]ports/, ~/[Tt]eams?/]] ],
	[answer:"Stadium", plain:["Stadiums"], needle:[[~/[Ss]tadiums?/]] ],
	[answer:"Station", plain:["Stations"], needle:[[~/[Ss]tations?/]] ],
	[answer:"SupremeCourtOfTheUnitedStatesCase", plain:[], needle:[[]] ],
	[answer:"SoccerPlayer", plain:["Soccer Players"], needle:[[~/[Ss]occer/, ~/[Pp]layers?/]] ],
	[answer:"Senator", plain:["Senators"], needle:[[~/[Ss]enators?/]] ],
	[answer:"Ship", plain:["Ships","Boats"], needle:[[~/[Ss]hips?/],[~/[Bb]oats?/]] ],
	[answer:"TelevisionEpisode", plain:["TV Episodes"], needle:[['TV', ~/[Ee]pisodes?/]] ],
	[answer:"TelevisionShow", plain:["TV Shows"], needle:[[/TV/, ~/[Ss]hows?/]] ],
	[answer:"TennisPlayer", plain:["Tennis Players"], needle:[[~/[Tt]ennis/, ~/[Pp]layers?/]] ],
	[answer:"TradeUnion", plain:['Trade Unions'], needle:[[~/[Tt]rade/, ~/[Uu]nions?/]] ],
	[answer:"University", plain:["Universities"], needle:[[~/[Uu]niversit(?:y|ies)/]] ],
	[answer:"Vein", plain:["Veins"], needle:[[~/[Vv]eins?/] ]],
	[answer:"VideoGame", plain:["Videogames"], needle:[ [~/[Vv]ideogames?/]] ],
	[answer:"Weapon", plain:["Weapons"], needle:[[~/[Ww]eapons?/]] ],
	[answer:"Website", plain:["Websites"], needle: [[~/[Ww]ebsites?/]] ],
	[answer:"WineRegion", plain:["Wine regions"], needle:[[~/[Ww]ine/, ~/[Rr]egions?/]] ],
	[answer:"WomensTennisAssociationTournament", plain:[], needle:[[]] ],
	[answer:"Work", plain:[], needle: [[~/[Ee]ncyclopedias?/],[~/[Ss]culptures?/], 
	  [~/[Pp]aintings?/],[~/[Mm]asterpieces?/] ] ]  ,
	[answer:"WorldHeritageSite", plain:["World heritage sites"], needle:[[~/[Ww]orld/, ~/[Hh]eritage/, ~/[Ss]ites?/]] ],
	[answer:"Wrestler", plain:["Wrestlers"], needle:[[~/[Ww]restlers?/]] ],
	[answer:"WrestlingEvent", plain:["Wrestling Event"], needle:[["[Ww]restling","[Ee]vents?"]] ],
	[answer:"Writer", plain:["Writers"], needle:[[~/[Ss]creenplayers?/], [~/[Ww]riters?/],
	[~/[Cc]olunists?/], [~/[Rr]omancists?/]] ]
   ]


}